name: YARMM
version: '${version}'
main: io.tanguygab.yarmm.YARMM
author: Tanguygab
depend: [TAB]
api-version: '1.21'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
commands:
  yarmm:
    permission: yarmm.admin
    aliases:
      - mm
      - menus
